version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    # Тут подключаем volume к backend
    volumes:
      - static:/backend_static
      - media:/app/media/cats/images/
  frontend:
    env_file: .env
    build: ./frontend/
  gateway:
    build: ./nginx/
    # А тут подключаем volume со статикой к gateway
    volumes:
      - static:/staticfiles/
      - media:/app/media/cats/images/
    ports:
      - 8000:80 
